[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "26"
  NPM_VERSION = "12.0.2"

[[plugins]]
  package = "netlify-plugin-cloudinary"

  [plugins.inputs]
    imagesPath = "/static/media"

[[plugins]]
  package = "@netlify/plugin-lighthouse"
